# Generated by Django 6.0.3 on 2026-03-17 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontier',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscriptiontier',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subscriptiontier',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='subscriptiontier',
            name='features',
        ),
        migrations.RemoveField(
            model_name='subscriptiontier',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subscriptiontier',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='renews_at',
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
