export const APPLICATION_SUBMIT_REQUEST = 'APPLICATION_SUBMIT_REQUEST';
export const APPLICATION_SUBMIT_SUCCESS = 'APPLICATION_SUBMIT_SUCCESS';
export const APPLICATION_SUBMIT_FAIL = 'APPLICATION_SUBMIT_FAIL';
export const APPLICATION_LIST_SUCCESS = 'APPLICATION_LIST_SUCCESS';
