export const SUBSCRIPTION_TIERS_REQUEST = 'SUBSCRIPTION_TIERS_REQUEST';
export const SUBSCRIPTION_TIERS_SUCCESS = 'SUBSCRIPTION_TIERS_SUCCESS';
export const SUBSCRIPTION_TIERS_FAIL = 'SUBSCRIPTION_TIERS_FAIL';
export const SUBSCRIPTION_CREATE_REQUEST = 'SUBSCRIPTION_CREATE_REQUEST';
export const SUBSCRIPTION_CREATE_SUCCESS = 'SUBSCRIPTION_CREATE_SUCCESS';
export const SUBSCRIPTION_CREATE_FAIL = 'SUBSCRIPTION_CREATE_FAIL';
export const SUBSCRIPTION_TRANSACTIONS_SUCCESS = 'SUBSCRIPTION_TRANSACTIONS_SUCCESS';
